services:
  app:
    build: .
    container_name: api_app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: departments_db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"  
    networks:
      - app-net

  tests:
    build: .
    container_name: api_tests
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: departments_db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    command: go test ./... -v        
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: departments_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: departments_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - app-net

networks:
  app-net:



